Traceback (most recent call last):
  File "main.py", line 185, in <module>
    app.run(main)
  File "/opt/conda/envs/sjpark/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/opt/conda/envs/sjpark/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "main.py", line 166, in main
    train_generator, validation_generator, test_generator, voca = data.build_dataset(path, train_bs = batch_size, eval_bs = FLAGS.validation_batch_size)
  File "/workspace/KG+text/TransE-PyTorch-master/data.py", line 23, in build_dataset
    voca = {'node':{k:v for (v,k) in enumerate(open(os.path.join(path, "node_dict")).read().splitlines())},
FileNotFoundError: [Errno 2] No such file or directory: 'data/node_dict'
